// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxtACANl6k0S3b_QOjxQtSLc6-4u4EqiQ',
    appId: '1:406727161324:web:689d945a7d3cd48abb3cc9',
    messagingSenderId: '406727161324',
    projectId: 'smartquail-18658',
    authDomain: 'smartquail-18658.firebaseapp.com',
    databaseURL: 'https://smartquail-18658-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartquail-18658.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1WMZCjkk2n2MbNH7K-18Dn2xu0Qo1SfU',
    appId: '1:406727161324:android:398efa5da2b7103ebb3cc9',
    messagingSenderId: '406727161324',
    projectId: 'smartquail-18658',
    databaseURL: 'https://smartquail-18658-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartquail-18658.firebasestorage.app',
  );
}
